# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: led_ctlr.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='led_ctlr.proto',
  package='led_ctlr',
  syntax='proto3',
  serialized_options=b'\n\030io.grpc.rpiledcontrollerB\020RPiLEDControllerP\001\242\002\003PIL',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eled_ctlr.proto\x12\x08led_ctlr\"=\n\nRPiRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x63olour\x18\x02 \x01(\x05\x12\x11\n\toperation\x18\x03 \x01(\x05\"\x1b\n\x08RPiReply\x12\x0f\n\x07message\x18\x01 \x01(\t2A\n\x08RPi_Ctlr\x12\x35\n\x07SendMsg\x12\x14.led_ctlr.RPiRequest\x1a\x12.led_ctlr.RPiReply\"\x00\x42\x34\n\x18io.grpc.rpiledcontrollerB\x10RPiLEDControllerP\x01\xa2\x02\x03PILb\x06proto3'
)




_RPIREQUEST = _descriptor.Descriptor(
  name='RPiRequest',
  full_name='led_ctlr.RPiRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='led_ctlr.RPiRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='colour', full_name='led_ctlr.RPiRequest.colour', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='operation', full_name='led_ctlr.RPiRequest.operation', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=89,
)


_RPIREPLY = _descriptor.Descriptor(
  name='RPiReply',
  full_name='led_ctlr.RPiReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='led_ctlr.RPiReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=118,
)

DESCRIPTOR.message_types_by_name['RPiRequest'] = _RPIREQUEST
DESCRIPTOR.message_types_by_name['RPiReply'] = _RPIREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RPiRequest = _reflection.GeneratedProtocolMessageType('RPiRequest', (_message.Message,), {
  'DESCRIPTOR' : _RPIREQUEST,
  '__module__' : 'led_ctlr_pb2'
  # @@protoc_insertion_point(class_scope:led_ctlr.RPiRequest)
  })
_sym_db.RegisterMessage(RPiRequest)

RPiReply = _reflection.GeneratedProtocolMessageType('RPiReply', (_message.Message,), {
  'DESCRIPTOR' : _RPIREPLY,
  '__module__' : 'led_ctlr_pb2'
  # @@protoc_insertion_point(class_scope:led_ctlr.RPiReply)
  })
_sym_db.RegisterMessage(RPiReply)


DESCRIPTOR._options = None

_RPI_CTLR = _descriptor.ServiceDescriptor(
  name='RPi_Ctlr',
  full_name='led_ctlr.RPi_Ctlr',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=120,
  serialized_end=185,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendMsg',
    full_name='led_ctlr.RPi_Ctlr.SendMsg',
    index=0,
    containing_service=None,
    input_type=_RPIREQUEST,
    output_type=_RPIREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RPI_CTLR)

DESCRIPTOR.services_by_name['RPi_Ctlr'] = _RPI_CTLR

# @@protoc_insertion_point(module_scope)
