# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import led_ctlr_pb2 as led__ctlr__pb2


class RPi_CtlrStub(object):
    """The RPi controller service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMsg = channel.unary_unary(
                '/led_ctlr.RPi_Ctlr/SendMsg',
                request_serializer=led__ctlr__pb2.RPiRequest.SerializeToString,
                response_deserializer=led__ctlr__pb2.RPiReply.FromString,
                )


class RPi_CtlrServicer(object):
    """The RPi controller service definition.
    """

    def SendMsg(self, request, context):
        """Sends a LED control message
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RPi_CtlrServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendMsg': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMsg,
                    request_deserializer=led__ctlr__pb2.RPiRequest.FromString,
                    response_serializer=led__ctlr__pb2.RPiReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'led_ctlr.RPi_Ctlr', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RPi_Ctlr(object):
    """The RPi controller service definition.
    """

    @staticmethod
    def SendMsg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/led_ctlr.RPi_Ctlr/SendMsg',
            led__ctlr__pb2.RPiRequest.SerializeToString,
            led__ctlr__pb2.RPiReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
